### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by BinGSSJ** [xbresson/TSP_Transformer#1]
Hi, 
I want to know **how long** it will take to train this model.
You set the **epoch = 10000**, and the depth of model is also twice that of Kool et-al,  so I think the good results are probably due to this reason.May I ask if you have used the model of Kool et-al to do comparative experiment under the same super parameter setting?

**Comment by xbresson** [comment]
with the same setting (including same numbers of encoding and decoding layers, and hidden dim) and 100 epochs:
Kool-et.al : L_train: 8.063, L_base: 8.054
Our model : L_train: 8.020, L_base: 8.021

**Comment by BinGSSJ** [comment]
Thanks!
